/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.foodweb.View.Produtos;

import com.mycompany.foodweb.Model.Categoria;
import com.mycompany.foodweb.Model.Restaurante;
import com.mycompany.foodweb.Service.CategoriaService;
import com.mycompany.foodweb.Service.RestauranteService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class JifCategorias extends javax.swing.JInternalFrame {
    
    private static JifCategorias internalFrameCategorias;
    private static Long idRestauranteRecuperado;

    public static JifCategorias getInstancia(Long idRestaurante) {
        if (internalFrameCategorias == null) {
            internalFrameCategorias = new JifCategorias(idRestaurante);
        }
        idRestauranteRecuperado = idRestaurante;        
        return internalFrameCategorias;
    }
    
    public JifCategorias(Long idRestaurante) {
        initComponents();
        
        this.setTitle("Categorias");
        
        tabelaCategorias.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabelaCategorias.getTableHeader().setOpaque(false);
        tabelaCategorias.getTableHeader().setBackground(new Color(32, 136, 203));
        tabelaCategorias.getTableHeader().setForeground(Color.WHITE);
        tabelaCategorias.setRowHeight(25);
        tabelaCategorias.setShowVerticalLines(false);
        
        preencherCategoriasNaTabela(idRestaurante);
        
    }
    
    public void preencherCategoriasNaTabela(Long idRestaurante) {
        
        Categoria[] listaDeCategorias = new CategoriaService().pegaCategoriasDoRestaurante(idRestaurante);
        
        DefaultTableModel tabela = (DefaultTableModel) tabelaCategorias.getModel();
        
        tabela.setRowCount(0);
        
        if (listaDeCategorias == null) {
            JOptionPane.showMessageDialog(null, "Erro ao buscar categorias!");
        } else {
            
            for (int i = 0; i < listaDeCategorias.length; i++) {
                tabela.addRow(new Object[] {
                    listaDeCategorias[i].getId(),
                    listaDeCategorias[i].getNome(),
                    listaDeCategorias[i].getAtivo()
                });
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCategorias = new javax.swing.JTable();
        buttonEditarCategoria = new javax.swing.JButton();
        buttonNovaCategoria1 = new javax.swing.JButton();
        buttonAtualizarCategorias = new javax.swing.JButton();

        tabelaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCategorias);

        buttonEditarCategoria.setBackground(new java.awt.Color(0, 153, 255));
        buttonEditarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditarCategoria.setText("Editar");
        buttonEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarCategoriaActionPerformed(evt);
            }
        });

        buttonNovaCategoria1.setBackground(new java.awt.Color(0, 153, 255));
        buttonNovaCategoria1.setForeground(new java.awt.Color(255, 255, 255));
        buttonNovaCategoria1.setText("Novo");
        buttonNovaCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovaCategoria1ActionPerformed(evt);
            }
        });

        buttonAtualizarCategorias.setBackground(new java.awt.Color(0, 153, 255));
        buttonAtualizarCategorias.setForeground(new java.awt.Color(255, 255, 255));
        buttonAtualizarCategorias.setText("Atualizar");
        buttonAtualizarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarCategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAtualizarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNovaCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNovaCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAtualizarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarCategoriaActionPerformed
        int linhaSelecionada = tabelaCategorias.getSelectedRow();
        if (linhaSelecionada != -1) {
            Long idCategoria = Long.valueOf(tabelaCategorias.getValueAt(linhaSelecionada, 0).toString());
            if (idCategoria != 0) {
                JifEditarCategoria internalFrameEditarCategoria = new JifEditarCategoria(idCategoria);
                getParent().add(internalFrameEditarCategoria);
                internalFrameEditarCategoria.setVisible(true);
                internalFrameEditarCategoria.setClosable(true);                
            }
        }        
    }//GEN-LAST:event_buttonEditarCategoriaActionPerformed

    private void buttonNovaCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovaCategoria1ActionPerformed
        
        RestauranteService restauranteService = new RestauranteService();
        CategoriaService categoriaService = new CategoriaService();
        Restaurante restaurante = restauranteService.consultarRestaurantePorId(idRestauranteRecuperado);
        JTextField textFieldNome = new JTextField();
        
        Object[] novaCategoria = {
            "Nome da categoria: ", textFieldNome
        };
        
        int option = JOptionPane.showConfirmDialog(this, novaCategoria, "Nova categoria", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            String nomeCategoria = textFieldNome.getText();
            Categoria categoria = new Categoria(nomeCategoria, true, restaurante);
            categoriaService.adicionarNovaCategoria(categoria);
            preencherCategoriasNaTabela(idRestauranteRecuperado);
        }
        
    }//GEN-LAST:event_buttonNovaCategoria1ActionPerformed

    private void buttonAtualizarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtualizarCategoriasActionPerformed
        preencherCategoriasNaTabela(idRestauranteRecuperado);
    }//GEN-LAST:event_buttonAtualizarCategoriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtualizarCategorias;
    private javax.swing.JButton buttonEditarCategoria;
    private javax.swing.JButton buttonNovaCategoria1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCategorias;
    // End of variables declaration//GEN-END:variables
}
