/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.foodweb.View.Produtos;

import com.mycompany.foodweb.Model.Categoria;
import com.mycompany.foodweb.Model.Restaurante;
import com.mycompany.foodweb.Service.CategoriaService;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public final class JifEditarCategoria extends javax.swing.JInternalFrame {
    
    Long idCategoria;

    /**
     * Creates new form JifEditarCategoria
     * @param idCategoria
     */
    public JifEditarCategoria(Long idCategoria) {
        initComponents();
        this.idCategoria = idCategoria;
        carregaCategoriaParaEdicao(idCategoria);
    }
    
    public void carregaCategoriaParaEdicao(Long idCategoria) {
        
        try {
            
            CategoriaService categoriaService = new CategoriaService();
            Categoria categoria = categoriaService.pegaCategoriaPorId(idCategoria);
            
            tfNomeCategoria.setText(categoria.getNome());
            
            DefaultComboBoxModel comboBoxSituacao = (DefaultComboBoxModel) comboBoxSituacaoCategoria.getModel();
            comboBoxSituacao.removeAllElements();
            
            boolean categoriaAtiva = categoria.getAtivo();
            if (categoriaAtiva) {
                comboBoxSituacao.addElement("Ativo");
                comboBoxSituacao.addElement("Desativado");
            } else {
                comboBoxSituacao.addElement("Desativado");
                comboBoxSituacao.addElement("Ativo");
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar as informações da categoria.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfNomeCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboBoxSituacaoCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buttonSalvarCategoria = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel1.setText("Nome");

        comboBoxSituacaoCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Situação");

        buttonSalvarCategoria.setText("Salvar");
        buttonSalvarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomeCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(comboBoxSituacaoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(buttonSalvarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxSituacaoCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(tfNomeCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(buttonSalvarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarCategoriaActionPerformed
        CategoriaService categoriaService = new CategoriaService();
        
        Restaurante restaurante = categoriaService.pegaCategoriaPorId(idCategoria).getRestaurante();
        
        String situacaoCategoria = comboBoxSituacaoCategoria.getSelectedItem().toString();
        
        Categoria categoria = new Categoria();
        categoria.setNome(tfNomeCategoria.getText());
        
        boolean categoriaAtivo = situacaoCategoria == "Ativo";
        
        categoria.setAtivo(categoriaAtivo);
        categoria.setRestaurante(restaurante);
        
        boolean categoriaAtualizada = categoriaService.atualizaCategoriaPorId(idCategoria, categoria);
        
        if (categoriaAtualizada) {
            JOptionPane.showMessageDialog(null, "Categoria editada com sucesso!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao editar categoria.");
        }
    }//GEN-LAST:event_buttonSalvarCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSalvarCategoria;
    private javax.swing.JComboBox<String> comboBoxSituacaoCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfNomeCategoria;
    // End of variables declaration//GEN-END:variables
}
