/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.foodweb.View.Produtos;

import com.mycompany.foodweb.Model.Categoria;
import com.mycompany.foodweb.Model.Produto;
import com.mycompany.foodweb.Model.Restaurante;
import com.mycompany.foodweb.Service.ProdutoService;
import com.mycompany.foodweb.Service.RestauranteService;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Rafael
 */
public class JifEditarProduto extends javax.swing.JInternalFrame {
    
    int idAtualProduto;
    String nomeAtualProduto;
    List<Categoria> listaCategorias;
    String descricaoAtualProduto;
    String precoAtualProduto;
    String quantidadeAtualProduto;
    
    Long idRestaurante;
    
    public JifEditarProduto(Long idRestaurante) {
        initComponents();
        this.setTitle("Editar Produto");
        preencheComboBoxCategorias(idRestaurante);
    }
    
    private void preencheComboBoxCategorias(Long idRestaurante) {
        DefaultComboBoxModel comboBox = (DefaultComboBoxModel) comboBoxCategoriaDoProduto.getModel();
        comboBox.removeAllElements();
        
        RestauranteService restauranteService = new RestauranteService();
        Categoria[] listaDeCategorias = restauranteService.listaCategoriasDoRestaurante(idRestaurante);
        
        for (int i = 0; i < listaDeCategorias.length; i++) {
            Categoria categoria = listaDeCategorias[i];
            comboBox.addElement(categoria);
        }
    }
    
    public void carregaProdutoParaEdicao(int idProduto) {
        
        try {
            
            ProdutoService produtoService = new ProdutoService();
            Produto produto = produtoService.pegaProdutoPorId(idProduto);
            
            idRestaurante = produto.getRestaurante().getId();

            RestauranteService restauranteService = new RestauranteService();
            Restaurante restaurante = restauranteService.consultarRestaurantePorId(idRestaurante);
            
            idAtualProduto = produto.getId();
            nomeAtualProduto = produto.getNome();
            listaCategorias = produto.getCategorias();
            descricaoAtualProduto = produto.getDescricao();
            quantidadeAtualProduto = produto.getQuantidade().toString();

            textFieldCodigoProduto.setText(Integer.toString(produto.getId()));
            textFieldNomeProduto.setText(produto.getNome());
            comboBoxCategoriaDoProduto.setSelectedItem(produto.getCategorias());
            textAreaDescricaoProduto.setText(produto.getDescricao());
            textFieldPrecoProduto.setText(Double.toString(produto.getPreco())); 
            textFieldQuantidadeProduto.setText(quantidadeAtualProduto);
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar as informações do produto.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textFieldNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescricaoProduto = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        textFieldPrecoProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldQuantidadeProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textFieldCodigoProduto = new javax.swing.JTextField();
        comboBoxCategoriaDoProduto = new javax.swing.JComboBox<>();
        buttonEditarProduto = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Imagem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jButton1.setText("Alterar imagem");

        jLabel2.setText("Nome");

        jLabel3.setText("Categoria");

        jLabel4.setText("Descrição");

        textAreaDescricaoProduto.setColumns(20);
        textAreaDescricaoProduto.setRows(5);
        jScrollPane1.setViewportView(textAreaDescricaoProduto);

        jLabel5.setText("Preço");

        textFieldPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPrecoProdutoActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantidade");

        jLabel7.setText("Código");

        textFieldCodigoProduto.setEditable(false);

        comboBoxCategoriaDoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(textFieldNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(185, 185, 185))
                                    .addComponent(comboBoxCategoriaDoProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textFieldPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(textFieldCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCategoriaDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        buttonEditarProduto.setText("Salvar edição");
        buttonEditarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEditarProdutoMouseClicked(evt);
            }
        });
        buttonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(buttonEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPrecoProdutoActionPerformed

    private void buttonEditarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEditarProdutoMouseClicked
        // TODO add your handling code here:
        Categoria categoria = (Categoria) comboBoxCategoriaDoProduto.getSelectedItem();
        List<Categoria> listaDeCategorias = new ArrayList<>();
        listaDeCategorias.add(categoria);
        
        int novoIdProduto = Integer.parseInt(textFieldCodigoProduto.getText());
        String novoNomeProduto = textFieldNomeProduto.getText();
        String novaDescricaoProduto = textAreaDescricaoProduto.getText();
        String novoPrecoProduto = textFieldPrecoProduto.getText();
        String novaQuantidadeProduto = textFieldQuantidadeProduto.getText();
        
        if (novoNomeProduto != nomeAtualProduto
            || novoPrecoProduto != precoAtualProduto
            || novaQuantidadeProduto != quantidadeAtualProduto) {
            
            RestauranteService restauranteService = new RestauranteService();
            Restaurante restaurante = restauranteService.consultarRestaurantePorId(idRestaurante);
            
            ProdutoService produtoService = new ProdutoService();            
            Produto produtoAlterado = new Produto(novoNomeProduto, novaDescricaoProduto, Double.valueOf(novoPrecoProduto), Double.valueOf(novaQuantidadeProduto), "www.url.com", restaurante, listaDeCategorias);            
            Boolean produtoAtualizado = produtoService.atualizaProdutoPorId(novoIdProduto, produtoAlterado);
            
            if (produtoAtualizado) {
                JOptionPane.showMessageDialog(null, "Produto editado com sucesso!");
                this.dispose();
            } else {                
                JOptionPane.showMessageDialog(null, "Erro ao editar produto. Por favor, tente novamente.");
            }
            
        }
        
    }//GEN-LAST:event_buttonEditarProdutoMouseClicked

    private void buttonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarProdutoActionPerformed
        // TODO add your handling code here:
        
        Categoria categoria = (Categoria) comboBoxCategoriaDoProduto.getSelectedItem();
        List<Categoria> listaDeCategorias = new ArrayList<>();
        listaDeCategorias.add(categoria);
        
        int novoIdProduto = Integer.parseInt(textFieldCodigoProduto.getText());
        String novoNomeProduto = textFieldNomeProduto.getText();
        String novaDescricaoProduto = textAreaDescricaoProduto.getText();
        String novoPrecoProduto = textFieldPrecoProduto.getText();
        String novaQuantidadeProduto = textFieldQuantidadeProduto.getText();
        
        if (novoNomeProduto != nomeAtualProduto
            || novoPrecoProduto != precoAtualProduto
            || novaQuantidadeProduto != quantidadeAtualProduto) {
            
            RestauranteService restauranteService = new RestauranteService();
            Restaurante restaurante = restauranteService.consultarRestaurantePorId(idRestaurante);
            
            ProdutoService produtoService = new ProdutoService();            
            Produto produtoAlterado = new Produto(novoNomeProduto, novaDescricaoProduto, Double.valueOf(novoPrecoProduto), Double.valueOf(novaQuantidadeProduto), "www.url.com", restaurante, listaDeCategorias);            
            Boolean produtoAtualizado = produtoService.atualizaProdutoPorId(idAtualProduto, produtoAlterado);
            
            if (produtoAtualizado) {
                JOptionPane.showMessageDialog(null, "Produto editado com sucesso!");
                this.dispose();
            } else {                
                JOptionPane.showMessageDialog(null, "Erro ao editar produto. Por favor, tente novamente.");
            }
            
        }
        
    }//GEN-LAST:event_buttonEditarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditarProduto;
    private javax.swing.JComboBox<String> comboBoxCategoriaDoProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaDescricaoProduto;
    private javax.swing.JTextField textFieldCodigoProduto;
    private javax.swing.JTextField textFieldNomeProduto;
    private javax.swing.JTextField textFieldPrecoProduto;
    private javax.swing.JTextField textFieldQuantidadeProduto;
    // End of variables declaration//GEN-END:variables
}
